### ISSUE TITLE
Using Electron

### ISSUE THREAD

**Issue by b3of** [sin-tanaka/vue-quagga#2]
I get these errors when I try to use it on Electron:

Line 44 in Scanner.vue:
```
TypeError: Cannot read property 'width' of undefined
    at VueComponent.data (..\node_modules\vue-quaggajs\dist\webpack:\src\Scanner.vue:44:1)
```

Line 70 in Scanner.vue:
```
TypeError: Cannot read property 'indexOf' of undefined
    at getPixels (..\node_modules\get-pixels\node-pixels.js:141:17)
    at loadImages (..\node_modules\quagga\lib\webpack:\lib\input_stream.js:27:9)
    at Object.that.setInputStream (..\node_modules\quagga\lib\webpack:\lib\input_stream.js:91:9)
    at initInputStream (..\node_modules\quagga\lib\webpack:\src\quagga.js:69:18)
    at Object.init (..\node_modules\quagga\lib\webpack:\src\quagga.js:480:13)
    at VueComponent.mounted (..\node_modules\vue-quaggajs\dist\webpack:\src\Scanner.vue:70:1)
```

_______________________________
My code:

index.js:
```
import Vue from 'vue';
import App from './App.vue';
new Vue({
  el: '#app',
  render(h) {
    return h(App)
  }
});
```

App.vue:
```
<template>
 <quagga-scanner></quagga-scanner>
</template>

<script>
import { QuaggaScanner } from 'vue-quaggajs';

export default {
  data() {
    return {
      name: "n1"
    };
  },
  components: {
    QuaggaScanner
  }
};
</script>
```

 @sin-tanaka please help.

**Comment by sin-tanaka** [comment]
@Abo3ooF 
Hi.

Thanks for find this issue, and using this library!
Now I am investigating the cause, so please wait a while until the solution.

but it takes time a little to fix, it may be faster to incorporate the following sources and fix them to work rather than wait for resolution.

see this:
https://github.com/sin-tanaka/vue-quagga/blob/master/src/Scanner.vue

**Comment by jaumebalust** [comment]
Hi, 
I got this error and I solved it by overriding the default readerSize by passing it a prop.
`<quagga-scanner :onDetected="logIt" :readerSize="readerSize" :readerType="'ean_reader'"></quagga-scanner>`

and then it worked for me!
